name: Deploy React App
on: push 
jobs:
  test:
    strategy:
      matrix:
        node-version: [14,16]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repositore code
        uses: actions/checkout@v3 
      - name: Install dependecies
        run: npm ci
      - name: Test apllication
        run: npm run test



      
